### ISSUE TITLE
使用docker方法启动容器失败

### ISSUE THREAD

**Issue by kal1x** [zsdlove/Hades#7]
我先执行了：
```bash
docker build -t hades .
```
在执行这里的时候报错：
```bash
docker run -p 8088:8088 hades
```

```bash
Running hooks in /etc/ca-certificates/update.d...

done.
done.
依赖安装完毕
Traceback (most recent call last):
  File "Hades-cli.py", line 17, in <module>
    from miniDVM.miniDVM import miniDVM
  File "/usr/src/app/miniDVM/miniDVM.py", line 17, in <module>
    from cfg.cfgManage import CFGBuilder
  File "/usr/src/app/cfg/cfgManage.py", line 7, in <module>
    from cfg.graphs import GraphManager
  File "/usr/src/app/cfg/graphs.py", line 4, in <module>
    import re, pydot
ImportError: No module named pydot

```

请问这是什么原因呢

**Comment by 404area** [comment]
同问

**Comment by knighttt7** [comment]
同问+1
